# Generated by Django 3.2.5 on 2021-07-29 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StressThis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='words',
            name='article',
            field=models.TextField(default='*калі будзе што, то дадам*'),
        ),
        migrations.AlterField(
            model_name='words',
            name='example',
            field=models.TextField(default='*калі будзе што, то дадам*'),
        ),
    ]
